version: '3'
services:
  spring-app:
    image: docker.io/prachitij/encryption:latest
    restart: unless-stopped
    container_name: encryption
    ports:
      - 11010:9004
#    volumes:
#      - ${logPath}/logs:/app/logs
#    environment:
#      - logPath=/app/logs
#      - env=${ENV}
#      - LOG_LEVEL=${LOG_LEVEL}   
    environment: 
      SPRING_PROFILES_ACTIVE: local